---
- name: Hello World!
  hosts: localhost
 
  tasks:
  # shell: curl -k "https://{{ url }}/api/v2/postMessage" --header 'Content-Type: application/json' --header 'X-Chatops-Source-Id: "{{ sourceId }}"' --header 'X-Chatops-Source-Api-Token: "{{ apiToken }}"' --header 'X-Transaction-Id: postmessage101' --data-raw '{ "workspaceName": "'"{{ workspaceName }}"'", "message": {"text":"'"{{ message }}"'"},"channelId": "'"{{ channelId }}"'"}'
  # shell: echo "Analysing ssl certs"
  - name: post to chatops
    uri:
      url: https://{{ url }}/api/v2/postMessage
      method: POST
      body: '{"message":{"text":"{{ message }}"},"channelId": "{{ channelId }}","collabPlatform": "TEAMS","workspaceName": "{{ workspaceName }}"}'
      body_format: json
      headers:
        Content-Type: "application/json"
        user-agent : "chatops"
        X-Chatops-Source-Id: "{{ sourceId }}"
        X-Chatops-Source-Api-Token: "{{ apiToken }}"
        X-Transaction-Id: "postmessage101"
        dest-id: "chatop"
        User-Agent : "servicenow"
  - name: Make sure service has time to start or stop
    pause:
      seconds: 3
      
  # shell: echo "ssl certs upgrade successfull."  
  - name: post to chatops2
    uri:
      url: https://{{ url }}/api/v2/postMessage
      method: POST
      body: '{"message":{"text":"{{ message1 }}"},"channelId": "{{ channelId }}","collabPlatform": "TEAMS","workspaceName": "{{ workspaceName }}"}'
      body_format: json
      headers:
        Content-Type: "application/json"
        user-agent : "chatops"
        X-Chatops-Source-Id: "{{ sourceId }}"
        X-Chatops-Source-Api-Token: "{{ apiToken }}"
        X-Transaction-Id: "postmessage101"
        dest-id: "chatop"
        User-Agent : "servicenow"
